language: ruby
bundler_args: --without deployment import unicorn newrelic
env: RACK_ENV=travis
before_script: cp ./config/example_ditty.yml ./config/ditty.yml
script: bundle exec rspec -c -fd
rvm:
  - 1.9.2
  - 1.9.3
  - ruby-head

