default:
  database: ditty
  table: posts
  title: "My little Ditty's!"
test:
  database: ditty_test
  table: rspec
#production:
  #database: ditty_production
  #table: posts
  #title: Your title!
  
