default:
  title: "My little Ditty's!"
development:
  auth:
    username: dev
    password: dev
test: 
  title: "My TEST Ditty's!"
  database: 
    name: ditty_test
    table: ditty_test
    username: test
    password: test
  auth:
    username: test
    password: test
travis:
  title: "My TEST Ditty's!"
  database: 
    name: ditty_travis
    table: ditty_travis
  auth:
    username: test
    password: test
stage:
  title: "blog.mervine.net"
  database: 
    name: ditty_stage
    table: blog
    username: stage
    password: stage
  auth:
    username: test
    password: test
#production:
  #database: ditty_production
  #table: ditty
  #title: Your title!
  #auth:
    #username: setme
    #password: setme
  
