# VALID OPTIONS
#
# <RACK_ENV>:
#   title: <blog title>
#   database:
#     name: <database name>
#     username: <database username>
#     password: <database password>
#   auth:
#     username: <http auth username>
#     password: <http auth password>
#   timezone: <defaults to "America/Los_Angeles">
#           #see http://tzinfo.rubyforge.org/ for details
#   google_analytics: <track id>

test: 
  title: "My TEST Ditty's!"
  database: 
    name: ditty_test
    username: test
    password: test
  auth:
    username: test
    password: test
  #timezone: "America/Los_Angeles"
  google_analytics: google_analytics_track_id
travis:
  title: "My TEST Ditty's!"
  database: 
    name: ditty_travis
  auth:
    username: test
    password: test
stage:
  title: "blog.mervine.net"
  database: 
    name: ditty_stage
    username: stage
    password: stage
  auth:
    username: test
    password: test
#production:
  #title: SET ME
  #database: 
    #name: production
    #username: setme
    #password: setme
  #auth:
    #username: setme
    #password: setme
  #timezone: "America/Los_Angeles" # default setting
  #google_analytics: <track id>

  
